import { PRODUCTS, money } from './catalog.js';
const STORAGE_KEY='cura-cart-v2';
const readCart=()=>{try{return JSON.parse(localStorage.getItem(STORAGE_KEY))||{}}catch{return{}}};
const writeCart=cart=>localStorage.setItem(STORAGE_KEY,JSON.stringify(cart));
export function initCart(){
  const drawer=document.querySelector('#cartDrawer'),scrim=document.querySelector('#scrim'),itemHost=document.querySelector('#cartItems'),empty=document.querySelector('#emptyCart'),footer=document.querySelector('#cartFooter'),subtotal=document.querySelector('#cartSubtotal'),toast=document.querySelector('#toast');
  const showToast=message=>{if(!toast)return;toast.textContent=message;toast.classList.add('visible');clearTimeout(showToast.timer);showToast.timer=setTimeout(()=>toast.classList.remove('visible'),2200)};
  const render=()=>{const cart=readCart(),entries=Object.entries(cart).filter(([,q])=>q>0),count=entries.reduce((sum,[,q])=>sum+q,0);document.querySelectorAll('[data-cart-count]').forEach(el=>el.textContent=count);if(!itemHost)return;empty.style.display=entries.length?'none':'flex';footer.style.display=entries.length?'block':'none';itemHost.innerHTML=entries.map(([id,q])=>{const p=PRODUCTS.find(x=>x.id===id);return p?`<div class="cart-item"><a href="./product.html?id=${p.id}"><img src="${p.image}" alt="${p.name}"></a><div><a href="./product.html?id=${p.id}"><h3>${p.name}</h3></a><p>${p.size}</p><div class="cart-quantity"><button data-cart-minus="${p.id}">−</button><span>${q}</span><button data-cart-plus="${p.id}">+</button></div></div><span class="cart-line-price">${money(p.price*q)}</span></div>`:''}).join('');subtotal.textContent=money(entries.reduce((sum,[id,q])=>{const p=PRODUCTS.find(x=>x.id===id);return sum+(p?p.price*q:0)},0))};
  const open=()=>{drawer?.classList.add('open');drawer?.setAttribute('aria-hidden','false');scrim?.classList.add('visible');document.body.classList.add('no-scroll')};
  const close=()=>{drawer?.classList.remove('open');drawer?.setAttribute('aria-hidden','true');scrim?.classList.remove('visible');document.body.classList.remove('no-scroll')};
  const add=(id,quantity=1,shouldOpen=false)=>{const cart=readCart();cart[id]=(cart[id]||0)+quantity;writeCart(cart);render();const p=PRODUCTS.find(x=>x.id===id);showToast(`${p?.name||'Item'} added to cart`);if(shouldOpen)open()};
  document.addEventListener('click',event=>{if(event.target.closest('[data-open-cart]'))open();if(event.target.closest('[data-close-cart]')||event.target===scrim)close();const plus=event.target.closest('[data-cart-plus]');if(plus)add(plus.dataset.cartPlus);const minus=event.target.closest('[data-cart-minus]');if(minus){const cart=readCart(),id=minus.dataset.cartMinus;cart[id]=Math.max(0,(cart[id]||0)-1);if(!cart[id])delete cart[id];writeCart(cart);render()}});
  document.addEventListener('keydown',event=>{if(event.key==='Escape')close()});render();return{add,open,close,render,showToast}
}
export function initMobileMenu(){const menu=document.querySelector('#mobileMenu'),openButton=document.querySelector('#mobileMenuButton'),closeButton=document.querySelector('#mobileMenuClose');if(!menu||!openButton||!closeButton)return;const setOpen=open=>{menu.classList.toggle('open',open);menu.setAttribute('aria-hidden',String(!open));openButton.setAttribute('aria-expanded',String(open));document.body.classList.toggle('no-scroll',open)};openButton.addEventListener('click',()=>setOpen(true));closeButton.addEventListener('click',()=>setOpen(false));menu.querySelectorAll('a').forEach(link=>link.addEventListener('click',()=>setOpen(false)))}
