export const PRODUCTS = [
  { id:'cream-cleanser', name:'Cream Cleanser', family:'Face', type:'Cleanser', concern:'Dryness', ingredient:'Amino Acids', texture:'Cream', price:38, size:'100 ml', sizes:['100 ml','200 ml'], badge:'Bestseller', subtitle:'Amino Acids & Squalane', image:'https://images.unsplash.com/photo-1571781926291-c477ebfd024b?auto=format&fit=crop&w=1200&q=88', description:'A gentle, hydrating cream cleanser that melts away impurities while maintaining the skin’s natural balance. Leaves skin soft, calm, and nourished.', ingredients:'Amino acids support the moisture barrier while olive-derived squalane helps soften and replenish dry or delicate skin.', benefits:'Cleanses without stripping, supports softness, helps reduce post-cleanse tightness, and leaves a comfortable finish.', use:'Massage one to two pumps onto damp skin. Rinse with warm water and pat dry. Use morning and evening.' },
  { id:'radiance-serum', name:'Radiance Serum', family:'Face', type:'Treatment', concern:'Dullness', ingredient:'Bakuchiol', texture:'Serum', price:72, size:'30 ml', sizes:['30 ml'], badge:'Bestseller', subtitle:'Bakuchiol & Niacinamide', image:'https://images.unsplash.com/photo-1620916566398-39f1143ab7be?auto=format&fit=crop&w=1200&q=88', description:'A concentrated daily serum created to brighten, refine, and visibly support a more even complexion without heaviness.', ingredients:'Bakuchiol, niacinamide, and a botanical antioxidant complex.', benefits:'Improves visible radiance, supports even tone, and softens the appearance of fine lines.', use:'Apply two to three drops after cleansing and before moisturizer.' },
  { id:'soothing-cream', name:'Soothing Cream', family:'Face', type:'Moisturizer', concern:'Sensitivity', ingredient:'Ceramides', texture:'Cream', price:58, size:'50 ml', sizes:['50 ml'], badge:'New', subtitle:'Ceramides & Oat Extract', image:'https://images.unsplash.com/photo-1598440947619-2c35fc9aa908?auto=format&fit=crop&w=1200&q=88', description:'A comforting daily moisturizer that supports a calm, resilient moisture barrier with a soft, non-greasy finish.', ingredients:'Ceramides, colloidal oat, and bisabolol.', benefits:'Comforts visible dryness, reduces the feeling of sensitivity, and locks in hydration.', use:'Press a small amount over face and neck after serum.' },
  { id:'gentle-body-wash', name:'Gentle Body Wash', family:'Body', type:'Cleanser', concern:'Dryness', ingredient:'Bergamot', texture:'Gel', price:36, size:'300 ml', sizes:['300 ml'], subtitle:'Bergamot & Black Pepper', image:'https://images.unsplash.com/photo-1556229010-6c3f2c9ca5f8?auto=format&fit=crop&w=1200&q=88', description:'A low-foam aromatic body cleanser that refreshes without disturbing the skin’s natural moisture balance.', ingredients:'Plant-derived surfactants with bergamot peel and black pepper extracts.', benefits:'Cleanses gently, refreshes, and leaves skin feeling balanced.', use:'Massage over wet skin and rinse thoroughly.' },
  { id:'hydrating-mist', name:'Hydrating Mist', family:'Face', type:'Essence', concern:'Dryness', ingredient:'Hyaluronic Acid', texture:'Mist', price:34, size:'120 ml', sizes:['120 ml'], subtitle:'Rose & Hyaluronic Acid', image:'https://images.unsplash.com/photo-1612817288484-6f916006741a?auto=format&fit=crop&w=1200&q=88', description:'A fine facial mist that restores immediate comfort and hydration throughout the day.', ingredients:'Multi-weight hyaluronic acid and rose water.', benefits:'Refreshes, hydrates, and prepares skin for treatment.', use:'Mist over clean skin or throughout the day as needed.' },
  { id:'daily-spf-30', name:'Daily SPF 30', family:'Face', type:'Protect', concern:'Environmental Stress', ingredient:'Zinc Oxide', texture:'Lotion', price:42, size:'50 ml', sizes:['50 ml'], subtitle:'Zinc Oxide & Squalane', image:'https://images.unsplash.com/photo-1556228578-8c89e6adf883?auto=format&fit=crop&w=1200&q=88', description:'A refined mineral sunscreen with a comfortable, moisturized finish designed for everyday wear.', ingredients:'Non-nano zinc oxide, squalane, and vitamin E.', benefits:'Broad-spectrum protection with a lightweight finish.', use:'Apply generously as the final step each morning. Reapply as needed.' },
  { id:'facial-oil', name:'Facial Oil', family:'Face', type:'Treatment', concern:'Dryness', ingredient:'Jojoba', texture:'Oil', price:68, size:'30 ml', sizes:['30 ml'], subtitle:'Squalane & Jojoba', image:'https://images.unsplash.com/photo-1608248543803-ba4f8c70ae0b?auto=format&fit=crop&w=1200&q=88', description:'A lightweight finishing oil that softens, replenishes, and enhances a healthy-looking glow.', ingredients:'Squalane, jojoba, and camellia seed oils.', benefits:'Seals in moisture and softens dry skin without a heavy feel.', use:'Warm two to three drops between hands and press over moisturizer.' },
  { id:'detox-clay-mask', name:'Detox Clay Mask', family:'Face', type:'Mask', concern:'Congestion', ingredient:'Kaolin', texture:'Clay', price:45, size:'60 ml', sizes:['60 ml'], subtitle:'Kaolin & Charcoal', image:'https://images.unsplash.com/photo-1601049541289-9b1b7bbbfe19?auto=format&fit=crop&w=1200&q=88', description:'A balancing clay treatment that clarifies without leaving skin feeling depleted.', ingredients:'Kaolin clay, bamboo charcoal, and glycerin.', benefits:'Absorbs excess oil and helps refine the look of pores.', use:'Apply a thin layer for ten minutes, then rinse. Use once or twice weekly.' },
  { id:'nourish-body-lotion', name:'Nourish Body Lotion', family:'Body', type:'Moisturizer', concern:'Dryness', ingredient:'Shea Butter', texture:'Lotion', price:42, size:'200 ml', sizes:['200 ml'], subtitle:'Shea Butter & Niacinamide', image:'https://images.unsplash.com/photo-1611930022073-b7a4ba5fcccd?auto=format&fit=crop&w=1200&q=88', description:'A fast-absorbing body lotion that leaves skin smooth, comfortable, and replenished.', ingredients:'Shea butter, niacinamide, and glycerin.', benefits:'Supports lasting moisture and improves the feel of rough, dry areas.', use:'Massage over clean skin daily.' },
  { id:'clarifying-shampoo', name:'Clarifying Shampoo', family:'Hair', type:'Cleanser', concern:'Buildup', ingredient:'Salicylic Acid', texture:'Gel', price:36, size:'250 ml', sizes:['250 ml'], subtitle:'Salicylic Acid & Rosemary', image:'https://images.unsplash.com/photo-1535585209827-a15fcdbc4c2d?auto=format&fit=crop&w=1200&q=88', description:'A focused scalp and hair cleanser that removes buildup while preserving softness.', ingredients:'Salicylic acid, rosemary leaf extract, and mild surfactants.', benefits:'Refreshes scalp and restores lightness to hair.', use:'Massage into wet scalp and hair. Rinse well. Use one to two times weekly.' },
  { id:'nourish-conditioner', name:'Nourish Conditioner', family:'Hair', type:'Conditioner', concern:'Dryness', ingredient:'Argan Oil', texture:'Cream', price:36, size:'250 ml', sizes:['250 ml'], subtitle:'Argan Oil & Pro-Vitamin B5', image:'https://images.unsplash.com/photo-1571875257727-256c39da42af?auto=format&fit=crop&w=1200&q=88', description:'A smoothing conditioner that softens lengths and supports manageable, healthy-looking hair.', ingredients:'Argan oil, panthenol, and oat protein.', benefits:'Improves softness, slip, and manageability.', use:'Apply through mid-lengths and ends, leave for two minutes, then rinse.' },
  { id:'hair-oil', name:'Hair Oil', family:'Hair', type:'Treatment', concern:'Dryness', ingredient:'Camellia', texture:'Oil', price:48, size:'30 ml', sizes:['30 ml'], subtitle:'Squalane & Camellia', image:'https://images.unsplash.com/photo-1608248543803-ba4f8c70ae0b?auto=format&fit=crop&w=1200&q=88', description:'A polished finishing oil that smooths flyaways and adds controlled shine without weight.', ingredients:'Camellia seed oil, squalane, and meadowfoam.', benefits:'Softens, smooths, and improves visible shine.', use:'Work one to three drops through damp or dry ends.' },
  { id:'renewing-aha-mask', name:'Renewing AHA Mask', family:'Face', type:'Mask', concern:'Texture', ingredient:'Lactic Acid', texture:'Gel Cream', price:62, size:'50 ml', sizes:['50 ml'], subtitle:'Lactic Acid & Licorice', image:'https://images.unsplash.com/photo-1598440947619-2c35fc9aa908?auto=format&fit=crop&w=1200&q=88', description:'A weekly resurfacing treatment for visibly smoother, brighter-looking skin.', ingredients:'Lactic acid, gluconolactone, and licorice root.', benefits:'Refines visible texture and supports brightness.', use:'Apply for five to eight minutes once weekly and rinse.' },
  { id:'body-oil', name:'Restorative Body Oil', family:'Body', type:'Treatment', concern:'Dryness', ingredient:'Jojoba', texture:'Oil', price:52, size:'100 ml', sizes:['100 ml'], subtitle:'Jojoba & Sea Buckthorn', image:'https://images.unsplash.com/photo-1608248543803-ba4f8c70ae0b?auto=format&fit=crop&w=1200&q=88', description:'A restorative body oil for supple, nourished skin with a satin finish.', ingredients:'Jojoba, sea buckthorn, and sunflower oils.', benefits:'Softens and replenishes while supporting elasticity.', use:'Massage into slightly damp skin after bathing.' },
  { id:'scalp-serum', name:'Scalp Serum', family:'Hair', type:'Treatment', concern:'Balance', ingredient:'Niacinamide', texture:'Serum', price:46, size:'50 ml', sizes:['50 ml'], subtitle:'Niacinamide & Green Tea', image:'https://images.unsplash.com/photo-1620916566398-39f1143ab7be?auto=format&fit=crop&w=1200&q=88', description:'A lightweight leave-in serum designed to comfort and balance the scalp.', ingredients:'Niacinamide, green tea, and panthenol.', benefits:'Supports a balanced scalp environment without residue.', use:'Apply directly to clean scalp and massage in. Do not rinse.' }
];
export const money = value => new Intl.NumberFormat('en-US',{style:'currency',currency:'USD',maximumFractionDigits:0}).format(value);
export const productById = id => PRODUCTS.find(product => product.id === id) || PRODUCTS[0];
