const images={hero:'https://images.unsplash.com/photo-1556228578-8c89e6adf883?auto=format&fit=crop&w=1800&q=88',cleanser:'https://images.unsplash.com/photo-1571781926291-c477ebfd024b?auto=format&fit=crop&w=1000&q=86',serum:'https://images.unsplash.com/photo-1620916566398-39f1143ab7be?auto=format&fit=crop&w=1000&q=86',cream:'https://images.unsplash.com/photo-1598440947619-2c35fc9aa908?auto=format&fit=crop&w=1000&q=86',spf:'https://images.unsplash.com/photo-1556229010-6c3f2c9ca5f8?auto=format&fit=crop&w=1000&q=86',skin:'https://images.unsplash.com/photo-1616394584738-fc6e612e71b9?auto=format&fit=crop&w=1400&q=86'};
const products=[{id:'gentle-cleanser',name:'Gentle Cleanser',price:38,size:'200 ml',category:'Cleanse',image:images.cleanser,description:'A low-foam botanical cleanser that removes impurities while preserving the skin’s natural moisture barrier.'},{id:'radiance-serum',name:'Radiance Serum',price:72,size:'30 ml',category:'Treat',image:images.serum,description:'A concentrated antioxidant serum that visibly brightens, supports elasticity, and restores an even appearance.'},{id:'soothing-cream',name:'Soothing Cream',price:58,size:'50 ml',category:'Hydrate',image:images.cream,description:'A comforting daily moisturizer with ceramides and calming botanicals for soft, balanced, resilient skin.'},{id:'daily-spf',name:'Daily SPF',price:36,size:'50 ml',category:'Protect',image:images.spf,description:'A lightweight broad-spectrum mineral sunscreen that protects without residue, fragrance, or heaviness.'},{id:'cream-cleanser',name:'Cream Cleanser',price:42,size:'100 ml',category:'Cleanse',image:images.hero,description:'A cushiony cream cleanser with amino acids and squalane, created for dry, delicate, or sensitized skin.'}];
const productGrid=document.querySelector('#productGrid'),cartDrawer=document.querySelector('#cartDrawer'),cartItems=document.querySelector('#cartItems'),cartFooter=document.querySelector('#cartFooter'),emptyCart=document.querySelector('#emptyCart'),scrim=document.querySelector('#scrim'),toast=document.querySelector('#toast'),cart=new Map();let activeProduct=null;
document.querySelector('.hero-image').style.backgroundImage=`url('${images.hero}')`;document.querySelector('.journal-image').style.backgroundImage=`url('${images.hero}')`;document.querySelector('.philosophy-image').style.backgroundImage=`url('${images.skin}')`;
const money=value=>new Intl.NumberFormat('en-US',{style:'currency',currency:'USD',maximumFractionDigits:0}).format(value);
function renderProducts(list=products.slice(0,4)){productGrid.innerHTML=list.map(p=>`<article class="product-card reveal" data-id="${p.id}"><div class="product-image-wrap" data-open-product="${p.id}" tabindex="0" role="button" aria-label="View ${p.name}"><img src="${p.image}" alt="CURA ${p.name}"><button class="quick-add" data-add="${p.id}">Add to cart</button></div><div class="product-meta"><div class="product-title"><h3>${p.name}</h3><span>${money(p.price)}</span></div><p>${p.category} · ${p.size}</p></div></article>`).join('');observeReveals()}
function showToast(message){toast.textContent=message;toast.classList.add('visible');clearTimeout(showToast.timer);showToast.timer=setTimeout(()=>toast.classList.remove('visible'),2200)}
function addToCart(id){cart.set(id,(cart.get(id)||0)+1);updateCart();showToast(`${products.find(p=>p.id===id).name} added to cart`)}
function updateCart(){const count=[...cart.values()].reduce((a,b)=>a+b,0);document.querySelectorAll('[data-cart-count]').forEach(el=>el.textContent=count);const entries=[...cart.entries()];emptyCart.style.display=entries.length?'none':'flex';cartFooter.style.display=entries.length?'block':'none';cartItems.innerHTML=entries.map(([id,qty])=>{const p=products.find(x=>x.id===id);return `<div class="cart-item"><img src="${p.image}" alt="${p.name}"><div><h3>${p.name}</h3><p>${p.size}</p><div class="quantity"><button data-qty="minus" data-id="${id}" aria-label="Decrease quantity">−</button><span>${qty}</span><button data-qty="plus" data-id="${id}" aria-label="Increase quantity">+</button></div></div><span class="cart-item-price">${money(p.price*qty)}</span></div>`}).join('');document.querySelector('#cartSubtotal').textContent=money(entries.reduce((sum,[id,qty])=>sum+products.find(p=>p.id===id).price*qty,0))}
function setDrawer(open){cartDrawer.classList.toggle('open',open);cartDrawer.setAttribute('aria-hidden',String(!open));scrim.classList.toggle('visible',open);document.body.classList.toggle('no-scroll',open)}
function openProduct(id){const shopId=id==='gentle-cleanser'?'cream-cleanser':id==='daily-spf'?'daily-spf-30':id;location.href=`./product.html?id=${shopId}`}
function setSearch(open){const el=document.querySelector('#searchOverlay');el.classList.toggle('open',open);el.setAttribute('aria-hidden',String(!open));document.body.classList.toggle('no-scroll',open);if(open){setTimeout(()=>document.querySelector('#searchInput').focus(),400);renderSearch('')}}
function renderSearch(query){const q=query.toLowerCase().trim(),result=products.filter(p=>!q||`${p.name} ${p.category} ${p.description}`.toLowerCase().includes(q));document.querySelector('#searchResults').innerHTML=result.map(p=>`<div class="search-result" data-open-product="${p.id}"><img src="${p.image}" alt="${p.name}"><p>${p.name} · ${money(p.price)}</p></div>`).join('')||'<p>No products found.</p>'}
function observeReveals(){if(!('IntersectionObserver'in window)){document.querySelectorAll('.reveal').forEach(el=>el.classList.add('visible'));return}const io=new IntersectionObserver(entries=>entries.forEach(e=>{if(e.isIntersecting){e.target.classList.add('visible');io.unobserve(e.target)}}),{threshold:.12});document.querySelectorAll('.reveal:not(.visible)').forEach(el=>io.observe(el))}
document.addEventListener('click',e=>{const add=e.target.closest('[data-add]');if(add){e.stopPropagation();addToCart(add.dataset.add);return}const open=e.target.closest('[data-open-product]');if(open){openProduct(open.dataset.openProduct);return}if(e.target.closest('[data-open-cart]'))setDrawer(true);if(e.target.closest('[data-close-cart]')||e.target===scrim)setDrawer(false);const qty=e.target.closest('[data-qty]');if(qty){const id=qty.dataset.id,next=(cart.get(id)||0)+(qty.dataset.qty==='plus'?1:-1);next<=0?cart.delete(id):cart.set(id,next);updateCart()}});
productGrid.addEventListener('keydown',e=>{if((e.key==='Enter'||e.key===' ')&&e.target.dataset.openProduct)openProduct(e.target.dataset.openProduct)});
document.querySelector('#modalClose').addEventListener('click',()=>document.querySelector('#productModal').close());document.querySelector('#modalAdd').addEventListener('click',()=>{addToCart(activeProduct.id);document.querySelector('#productModal').close();setDrawer(true)});document.querySelector('#searchButton').addEventListener('click',()=>setSearch(true));document.querySelector('#mobileSearchButton').addEventListener('click',()=>{setMobileMenu(false);setSearch(true)});document.querySelector('#searchClose').addEventListener('click',()=>setSearch(false));document.querySelector('#searchInput').addEventListener('input',e=>renderSearch(e.target.value));document.querySelector('#viewAllProducts').addEventListener('click',()=>location.href='./shop.html');document.querySelector('#checkoutButton').addEventListener('click',()=>showToast('Checkout is ready for payment integration'));document.querySelector('#newsletterForm').addEventListener('submit',e=>{e.preventDefault();document.querySelector('#newsletterMessage').textContent='Thank you. A note from CURA will arrive shortly.';e.target.reset()});
const mobileMenu=document.querySelector('#mobileMenu');function setMobileMenu(open){mobileMenu.classList.toggle('open',open);mobileMenu.setAttribute('aria-hidden',String(!open));document.querySelector('#mobileMenuButton').setAttribute('aria-expanded',String(open));document.body.classList.toggle('no-scroll',open)}document.querySelector('#mobileMenuButton').addEventListener('click',()=>setMobileMenu(true));document.querySelector('#mobileMenuClose').addEventListener('click',()=>setMobileMenu(false));mobileMenu.querySelectorAll('a').forEach(a=>a.addEventListener('click',()=>setMobileMenu(false)));document.addEventListener('keydown',e=>{if(e.key==='Escape'){setDrawer(false);setSearch(false);setMobileMenu(false);const modal=document.querySelector('#productModal');if(modal.open)modal.close()}});
document.querySelectorAll('a[href="#shop"]').forEach(link=>link.setAttribute('href','./shop.html'));
renderProducts();updateCart();observeReveals();