import { PRODUCTS, money } from './catalog.js';
import { initCart, initMobileMenu } from './cart.js';
const cart=initCart();initMobileMenu();
const grid=document.querySelector('#catalogGrid'),count=document.querySelector('#productCount'),pagination=document.querySelector('#pagination'),search=document.querySelector('#productSearch'),sort=document.querySelector('#sortSelect'),concern=document.querySelector('#concernFilter'),ingredient=document.querySelector('#ingredientFilter'),texture=document.querySelector('#textureFilter'),price=document.querySelector('#priceFilter');
const PAGE_SIZE=12;let activeFamily='Face',activePage=1;
function filteredProducts(){const query=search.value.toLowerCase().trim();let items=PRODUCTS.filter(p=>p.family===activeFamily);if(query)items=items.filter(p=>`${p.name} ${p.subtitle} ${p.type}`.toLowerCase().includes(query));if(concern.value)items=items.filter(p=>p.concern===concern.value);if(ingredient.value)items=items.filter(p=>p.ingredient===ingredient.value);if(texture.value)items=items.filter(p=>p.texture===texture.value);if(price.value==='under-40')items=items.filter(p=>p.price<40);if(price.value==='40-60')items=items.filter(p=>p.price>=40&&p.price<=60);if(price.value==='over-60')items=items.filter(p=>p.price>60);if(sort.value==='price-asc')items.sort((a,b)=>a.price-b.price);if(sort.value==='price-desc')items.sort((a,b)=>b.price-a.price);if(sort.value==='name')items.sort((a,b)=>a.name.localeCompare(b.name));return items}
function render(){const items=filteredProducts(),pageCount=Math.max(1,Math.ceil(items.length/PAGE_SIZE));activePage=Math.min(activePage,pageCount);const visible=items.slice((activePage-1)*PAGE_SIZE,activePage*PAGE_SIZE);count.textContent=`${items.length} product${items.length===1?'':'s'}`;grid.innerHTML=visible.map(p=>`<article class="catalog-card"><a class="catalog-link" href="./product.html?id=${p.id}" aria-label="View ${p.name}"><div class="catalog-image"><img src="${p.image}" alt="CURA ${p.name}">${p.badge?`<span class="product-badge">${p.badge}</span>`:''}</div><div class="catalog-info"><h2>${p.name}</h2><p>${p.subtitle}</p><strong>${money(p.price)}</strong></div></a><button class="quick-add-circle" data-quick-add="${p.id}" aria-label="Quick add ${p.name}">+</button></article>`).join('')||'<p>No products match these filters.</p>';pagination.innerHTML=pageCount>1?[`<button class="page-button" data-page="${Math.max(1,activePage-1)}">←</button>`,...Array.from({length:pageCount},(_,i)=>`<button class="page-button ${activePage===i+1?'active':''}" data-page="${i+1}">${i+1}</button>`),`<button class="page-button" data-page="${Math.min(pageCount,activePage+1)}">→</button>`].join(''):''}
document.querySelectorAll('[data-family]').forEach(button=>button.addEventListener('click',()=>{activeFamily=button.dataset.family;activePage=1;document.querySelectorAll('[data-family]').forEach(item=>item.classList.toggle('active',item===button));[concern,ingredient,texture,price].forEach(control=>control.value='');render()}));
[search,sort,concern,ingredient,texture,price].forEach(control=>control.addEventListener('input',()=>{activePage=1;render()}));
document.addEventListener('click',event=>{const quickAdd=event.target.closest('[data-quick-add]');if(quickAdd){event.preventDefault();cart.add(quickAdd.dataset.quickAdd)}const pageButton=event.target.closest('[data-page]');if(pageButton){activePage=Number(pageButton.dataset.page);render();window.scrollTo({top:150,behavior:'smooth'})}});
document.querySelector('#searchButton').addEventListener('click',()=>{search.focus();document.querySelector('#searchWrap').classList.add('open')});
document.querySelector('#shopNewsletter').addEventListener('submit',event=>{event.preventDefault();cart.showToast('Thank you for joining CURA');event.currentTarget.reset()});
render();
